## Objetivo:

1. encontrar el valor del magnetón de Bohr a partir de la distancia $\alpha$ de las líneas y el valor del campo magnético

In [2]:
#librerías a usar

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statistics as st
from scipy.optimize import curve_fit
from math import pi #to use on labeling
from fractions import Fraction #show the decimals as fractions
from scipy.constants import h , c
from scipy.constants import physical_constants

m_b = physical_constants['Bohr magneton'][0]

Lista de datos

In [3]:
B=np.array([1353,1253,1170,1096,980,853,701,560])
B=B*1e-3
d2=np.full(8,83)
d1=np.array([12.5,11.5,11,9.5,8,7.5,6.5,5.5])
#----
d=2.7e-3
h1=6.6260e-34
c1=3e8

In [4]:
mb_teo=np.full(8,m_b)
alfa_1 = d1/d2
print(np.round(alfa_1,3))

[0.151 0.139 0.133 0.114 0.096 0.09  0.078 0.066]


In [4]:
mag_bohr= (alfa_1*h1*c1)/(B*d)
print(mag_bohr)

[8.19488845e-24 8.14099708e-24 8.33945468e-24 7.68854005e-24
 7.24093654e-24 7.79907437e-24 8.22481557e-24 8.71175177e-24]


In [5]:
mb=(alfa_1*h*c)/(B*d)
print(mb)

[8.18930587e-24 8.13545122e-24 8.33377362e-24 7.68330241e-24
 7.23600381e-24 7.79376144e-24 8.21921261e-24 8.70581709e-24]


In [9]:
#array de errores

Error=abs(mb_teo-mag_bohr)*100/mb_teo
Error_const=abs(mb_teo-mb)*100/mb_teo
print(np.round(Error,3), np.round(np.mean(Error),3), '% error ')
print(np.round(Error_const,3), np.round(np.mean(Error_const),3), '% error con scipy')

[11.636 12.217 10.077 17.096 21.922 15.904 11.313  6.063] 13.279 % error 
[11.696 12.277 10.138 17.152 21.975 15.961 11.374  6.127] 13.338 % error con scipy
